core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_core.urls')),
    path('', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_core/urls.py
from django.urls import path

from . import views

app_name = 'crm_core'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('products/', views.products_view, name='products_view'),
    path('hx_add_order/', views.hx_add_order, name='hx_add_order'),
    path('hx_add_client/', views.hx_add_client, name='hx_add_client'),
    path('hx_add_product/', views.hx_add_product, name='hx_add_product'),
    path('hx_delete_product/<int:id>/', views.hx_delete_product, name='hx_delete_product'),
]

crm_core/models.py
from django.db import models

from accounts.models import CrmUser

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=1000)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    availability = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CrmUser, related_name='products', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ('-created_at',)


class Order(models.Model):

    ORDERED = 'ordered'
    DELIVERING = 'delivering'
    COMPLETED = 'completed'

    STATUS_CHOICES = (
        (ORDERED, 'Ordered'),
        (DELIVERING, 'Delivering'),
        (COMPLETED, 'Completed'),
    )

    client = models.ForeignKey(CrmUser, related_name='client_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    paid = models.BooleanField(default=False)
    paid_amount = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ORDERED)

    created_by = models.ForeignKey(CrmUser, related_name='orders', on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)
    
    def get_total(self):
        return sum(int(item.price) for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

crm_core/views.py
import time

from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from accounts.models import CrmUser
from . import models
from .helpers import prepare_pagination

# Create your views here.
@login_required(login_url='accounts:auth')
@staff_member_required(login_url='accounts:auth')
def home_view(request):
    template_name = 'crm_home.html'
    products = models.Product.objects.all()
    orders = models.Order.objects.all()
    clients = CrmUser.objects.filter(is_client=True)

    context = {
        'products': products,
        'orders': orders,
        'orders_count': orders.count(),
        'products_total': products.count(),
        'products_out_of_stock_total': products.filter(availability=False).count(),
        'clients': clients,
        'clients_total': clients.count(),
    }
    return render(request, template_name, context)


def products_view(request):
    template_name = 'products.html'
    context = {}

    products = models.Product.objects.all()

    query = request.GET.get("search", None)
    if query:
        products = models.Product.objects.filter(title__icontains=query)

    if request.htmx:
        time.sleep(1)
        template_name = 'partials/products_table_body.html'

    page = request.GET.get('page', 1)
    products, total_products = prepare_pagination(products, page, 3)

    context["products"] = products
    context["total_products"] = total_products

    return render(request, template_name, context)


def hx_add_order(request):
    partial_template_name = 'partials/add_order_form.html'

    return render(request, partial_template_name)


def hx_add_client(request):
    partial_template_name = 'partials/add_client_form.html'
    clients = None
    context = {}

    if request.method == 'POST':
        partial_template_name = 'partials/clients_list.html'

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')

        new_client = CrmUser.objects.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            phone=phone,
            is_client=True,
        )
        clients = CrmUser.objects.filter(is_client=True)
        context['clients'] = clients
        context['clients_total'] = clients.count()
        messages.add_message(request, messages.SUCCESS, 'New Client added!')

    return render(request, partial_template_name, context)


def hx_add_product(request):
    partial_template_name = 'partials/add_product_form.html'
    products = None
    context = {}

    if request.method == 'POST':
        partial_template_name = 'partials/products_list.html'

        title = request.POST.get('title')
        price = request.POST.get('price')
        description = request.POST.get('description')
        availability = False
        if request.POST.get('availability') == 'True':
            availability = True

        models.Product.objects.create(
            title=title,
            price=price,
            description=description,
            availability=availability,
            created_by=request.user
        )
        products = models.Product.objects.all()
        total_products = products.count()
        if request.POST.get('page', False):
            partial_template_name = 'partials/products_table_body.html'
            products, total_products = prepare_pagination(query=products, items_per_page=3)

        context = {
            'products': products,
            'products_total': total_products
        }
        if not request.POST.get('page', False):
            context['products_out_of_stock_total'] = products.filter(availability=False).count()
        messages.add_message(request, messages.SUCCESS, 'New Product added!')

    return render(request, partial_template_name, context)


def hx_delete_product(request, id):
    try:
        product = models.Product.objects.get(id=id)
        product.delete()
        messages.add_message(request, messages.WARNING, 'Product successfully deleted!')
    except models.Product.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'Product didn\'t exist...')
    partial_template_name = 'partials/products_table_body.html'
    products = models.Product.objects.all()
    products, total_products = prepare_pagination(query=products, items_per_page=3)

    context = {
        'products': products,
        'products_total': total_products
    }
    return render(request, partial_template_name, context)

crm_core/templates/partials/add_client_form.html
<form action="#" method="post" class="border border-1 p-3 rounded-custom mb-3">
    <div class="row">
        <div class="mb-3 col">
            <div class="mb-3 row">
                <div class="col">
                    <label for="first_name" class="form-label">First name</label>
                    <input type="text" name="first_name" id="first_name" class="form-control">
                    <div id="title" class="form-text">Input client first name.</div>
                </div>
                <div class="col">
                    <label for="last_name" class="form-label">Last name</label>
                    <input type="text" name="last_name" id="last_name" class="form-control">
                    <div id="last_name" class="form-text">Input client last name.</div>
                </div>
            </div>
            <!-- <div class="mb-3">
                <label for="userpic" class="form-label">Userpic</label>
                <input type="file" class="form-control" name="userpic" id="userpic">
                <div id="userpic" class="form-text">Select userpic for client.</div>
            </div> -->
        </div>
        <div class="mb-3 col">
            <div class="mb-3 row">
                <div class="col">
                    <label for="email" class="form-label">E-mail</label>
                    <input type="email" name="email" id="email" class="form-control">
                    <div id="email" class="form-text">Input client email.</div>
                </div>
                <div class="col">
                    <label for="phone" class="form-label">Phone</label>
                    <input type="phone" name="phone" id="phone" class="form-control">
                    <div id="phone" class="form-text">Input client phone.</div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="d-flex justify-content-between">
        <button type="submit"
            class="btn btn-primary"
            hx-post="{% url 'crm_core:hx_add_client' %}"
            hx-target="#clients-list"
            hx-swap="innerHTML">
            Submit
        </button>
        <button type="reset" onclick="removeForm(event)" class="btn btn-outline-warning">Cancel</button>
    </div>
</form>

crm_core/templates/partials/add_order_form.html
<form class="border border-1 p-3 rounded-custom mb-3">
    <div class="row">
        <div class="mb-3 col">
            <div class="mb-3">
                <label for="client" class="form-label">Client</label>
                <select name="client" id="client" class="form-select">
                  <option value="">Select client</option>
                </select>
                <div id="client" class="form-text">Select client for new order.</div>
            </div>
            <div class="mb-3 row">
                <div class="col">
                    <label for="address" class="form-label">Address</label>
                    <input type="text" name="address" id="address" class="form-control">
                    <div id="address" class="form-text">Input client address.</div>
                </div>
                <div class="col">
                    <label for="place" class="form-label">Place/City</label>
                    <input type="text" name="place" id="place" class="form-control">
                    <div id="place" class="form-text">Input client city.</div>
                </div>
            </div>
            <div class="mb-3">
                <div class="col">
                    <label for="zipcode" class="form-label">Zipcode</label>
                    <input type="text" name="zipcode" id="zipcode" class="form-control">
                    <div id="zipcode" class="form-text">Input client zipcode.</div>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" id="email" class="form-control">
                    <div id="email" class="form-text">Input client contact email address.</div>
                </div>
                <div class="col">
                    <label for="phone" class="form-label">Phone</label>
                    <input type="phone" name="phone" id="phone" class="form-control">
                    <div id="phone" class="form-text">Input client contact phone.</div>
                </div>
            </div>
        </div>
        <div class="mb-3 col">
            <div class="row mb-3">
                <div class="col-sm-10">
                    <label for="product" class="form-label">Products</label>
                    <select name="product" id="product" class="form-select">
                        <option value="">Select products</option>
                    </select>
                    <div id="product" class="form-text">Add products to new order.</div>
                </div>
                <div class="col">
                    <label for="client" class="form-label">Quantity</label>
                    <input type="number" name="quantity" id="quantity" min="1" class="form-control">
                </div>
                
            </div>
            <button type="button" class="btn btn-outline-success form-control">
                Add another Product
            </button>

        </div>
          
    </div>
    
    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" onclick="removeForm(event)" class="btn btn-outline-warning">Cancel</button>
    </div>
</form>

crm_core/templates/partials/add_product_form.html
<form action="#" method="post" class="border border-1 p-3 rounded-custom mb-3 bg-gray-200 rounded-md">
    <div class="row">
        <div class="mb-3 col">
            <div class="mb-3 row">
                <div class="col">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" name="title" id="title" class="form-control">
                    <div id="title" class="form-text">Input product title.</div>
                </div>
                <div class="col">
                    <label for="price" class="form-label">Price, $</label>
                    <input type="number" name="price" id="price" class="form-control" min="0">
                    <div id="price" class="form-text">Input product price.</div>
                </div>
            </div>
            <div class="mb-3">
                <label for="availability" class="form-label">Availability</label>
                <select name="availability" id="availability" class="form-select">
                    <option value="True">Yes</option>
                    <option value="False">No</option>
                </select>
            </div>
        </div>
        <div class="mb-3 col">
            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
                <div id="description" class="form-text">Input product description.</div>
            </div>
        </div>
    </div>
    
    <div class="d-flex justify-content-between">
        <button type="submit"
            class="btn bg-green-600 btn-sm text-white font-bold"
            hx-post="{% url 'crm_core:hx_add_product' %}"
            hx-target="#products-list"
            hx-swap="innerHTML">
            Submit
        </button>
        <button type="reset" onclick="removeForm(event)" class="btn btn-outline-warning">Cancel</button>
    </div>
</form>

crm_core/templates/partials/clients_list.html
{% for client in clients %}
    <li class="list-group-item d-flex justify-content-between align-items-center rounded-custom mb-1">
        <span>{{ client.get_full_name }}</span>
        <span>
            <button type="button" class="btn btn-outline-success btn-sm">
                Edit
            </button>
        </span>
    </li>
{% endfor %}

{% if request.htmx %}
    <div class="card" id="clients-card" hx-swap-oob="true">
        <div class="card-body border border-1 border-info">
        <h5 class="card-title">Clients</h5>
        <p class="card-text">Total: {{ clients_total }}</p>
        <p class="card-text">Active orders:</p>
        </div>
    </div>

    <div id="spawn-form" hx-swap-oob="true"></div>
{% endif %}

crm_core/templates/partials/orders_list.html
{% for order in orders %}
    <li class="list-group-item d-flex justify-content-between">
        <span>{{ order.id }}</span>
        <span>
            <button type="button" class="btn btn-outline-success btn-sm">
                Edit
            </button>
        </span>
    </li>
{% endfor %}

crm_core/templates/partials/paging_navigation.html
<nav id="nav_paging_navigation" hx-swap-oob="true:#nav_paging_navigation">
    
    <ul class="pagination justify-content-center mb-0">
        {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" id="prev_page" hx-get="?page={{ products.previous_page_number }}" hx-target="#table-body" hx-swap="innerHTML" hx-push-url="true" hx-indicator="#htmx-indicator">
                    Previous
                </a>
            </li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}
        {% for i in products.paginator.page_range %}
            {% if products.number == i %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ i }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" hx-get="?page={{ i }}" hx-target="#table-body" hx-swap="innerHTML" hx-push-url="true" hx-indicator="#htmx-indicator">
                        {{ i }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
        {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" id="next_page" hx-get="?page={{ products.next_page_number }}" hx-target="#table-body" hx-swap="innerHTML" hx-push-url="true" hx-indicator="#htmx-indicator">
                    Next
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
    </ul>
</nav>

crm_core/templates/partials/products_list.html
{% for product in products %}
    <li class="list-group-item d-flex justify-content-between align-items-center rounded-custom mb-1">
        <span>{{ product.title }}: ${{ product.price }}</span>
        <span>
            <button type="button" class="btn btn-outline-success btn-sm">
                Edit
            </button>
        </span>
    </li>
{% endfor %}

{% if request.htmx %}
    <div class="card" id="products-card" hx-swap-oob="true">
        <div class="card-body border border-1 border-info rounded-3 ">
            <h5 class="card-title">Products</h5>
            <p class="card-text">Total: {{ products_total }}</p>
            <p class="card-text">Not available: {{ products_out_of_stock_total }}</p>
        </div>
    </div>

    <div id="spawn-form" hx-swap-oob="true"></div> 
{% endif %}

crm_core/templates/partials/products_table_body.html
{% for product in products %}
    <tr class="bg-gray-100">
        <td>{{product.id}}</td>
        <td>{{product.title}}</td>
        <td>{{product.price}}</td>
        <td>{{product.availability}}</td>
        <td>{{product.created_at}}</td>
        <td>
            <button type="button" class="btn btn-outline-success btn-sm"

            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                  </svg>
                  
            </button>            
        </td>
        <td>
            <button type="button" class="btn btn-outline-danger btn-sm"
            hx-delete="{% url 'crm_core:hx_delete_product' id=product.id %}"
            hx-target="#table-body"
            hx-swap="innerHTML"
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                  </svg>                  
            </button>            
        </td>
    </tr>
{% endfor %}

{% if request.htmx %}
    {% include 'partials/paging_navigation.html' %}
{% endif %}