accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('auth/', views.auth, name='auth'),
    path("logout/", LogoutView.as_view(), name="logout"),

    path('hx_registration/', views.hx_registration, name='hx_registration'),
    path('hx_login/', views.hx_login, name='hx_login'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_core.urls')),
    path('', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_core/urls.py
from django.urls import path

from . import views

app_name = 'crm_core'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('products/', views.products_view, name='products_view'),
    path('hx_add_order/', views.hx_add_order, name='hx_add_order'),
    path('hx_add_client/', views.hx_add_client, name='hx_add_client'),
    path('hx_add_product/', views.hx_add_product, name='hx_add_product'),
    path('hx_delete_product/<int:id>/', views.hx_delete_product, name='hx_delete_product'),
]

crm_core/models.py
from django.db import models

from accounts.models import CrmUser

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=1000)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    availability = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CrmUser, related_name='products', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ('-created_at',)


class Order(models.Model):

    ORDERED = 'ordered'
    DELIVERING = 'delivering'
    COMPLETED = 'completed'

    STATUS_CHOICES = (
        (ORDERED, 'Ordered'),
        (DELIVERING, 'Delivering'),
        (COMPLETED, 'Completed'),
    )

    client = models.ForeignKey(CrmUser, related_name='client_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    paid = models.BooleanField(default=False)
    paid_amount = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ORDERED)

    created_by = models.ForeignKey(CrmUser, related_name='orders', on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)
    
    def get_total(self):
        return sum(int(item.price) for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

crm_core/views.py
import time

from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from accounts.models import CrmUser
from . import models
from .helpers import prepare_pagination

# Create your views here.
@login_required(login_url='accounts:auth')
@staff_member_required(login_url='accounts:auth')
def home_view(request):
    template_name = 'crm_home.html'
    products = models.Product.objects.all()
    orders = models.Order.objects.all()
    clients = CrmUser.objects.filter(is_client=True)

    context = {
        'products': products,
        'orders': orders,
        'orders_count': orders.count(),
        'products_total': products.count(),
        'products_out_of_stock_total': products.filter(availability=False).count(),
        'clients': clients,
        'clients_total': clients.count(),
    }
    return render(request, template_name, context)


def products_view(request):
    template_name = 'products.html'
    context = {}

    products = models.Product.objects.all()

    query = request.GET.get("search", None)
    if query:
        products = models.Product.objects.filter(title__icontains=query)

    if request.htmx:
        time.sleep(1)
        template_name = 'partials/products_table_body.html'

    page = request.GET.get('page', 1)
    products, total_products = prepare_pagination(products, page, 3)

    context["products"] = products
    context["total_products"] = total_products

    return render(request, template_name, context)


def hx_add_order(request):
    partial_template_name = 'partials/add_order_form.html'

    return render(request, partial_template_name)


def hx_add_client(request):
    partial_template_name = 'partials/add_client_form.html'
    clients = None
    context = {}

    if request.method == 'POST':
        partial_template_name = 'partials/clients_list.html'

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')

        new_client = CrmUser.objects.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            phone=phone,
            is_client=True,
        )
        clients = CrmUser.objects.filter(is_client=True)
        context['clients'] = clients
        context['clients_total'] = clients.count()
        messages.add_message(request, messages.SUCCESS, 'New Client added!')

    return render(request, partial_template_name, context)


def hx_add_product(request):
    partial_template_name = 'partials/add_product_form.html'
    products = None
    context = {}

    if request.method == 'POST':
        partial_template_name = 'partials/products_list.html'

        title = request.POST.get('title')
        price = request.POST.get('price')
        description = request.POST.get('description')
        availability = False
        if request.POST.get('availability') == 'True':
            availability = True

        models.Product.objects.create(
            title=title,
            price=price,
            description=description,
            availability=availability,
            created_by=request.user
        )
        products = models.Product.objects.all()
        total_products = products.count()
        if request.POST.get('page', False):
            partial_template_name = 'partials/products_table_body.html'
            products, total_products = prepare_pagination(query=products, items_per_page=3)

        context = {
            'products': products,
            'products_total': total_products
        }
        if not request.POST.get('page', False):
            context['products_out_of_stock_total'] = products.filter(availability=False).count()
        messages.add_message(request, messages.SUCCESS, 'New Product added!')

    return render(request, partial_template_name, context)


def hx_delete_product(request, id):
    try:
        product = models.Product.objects.get(id=id)
        product.delete()
        messages.add_message(request, messages.WARNING, 'Product successfully deleted!')
    except models.Product.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'Product didn\'t exist...')
    partial_template_name = 'partials/products_table_body.html'
    products = models.Product.objects.all()
    products, total_products = prepare_pagination(query=products, items_per_page=3)

    context = {
        'products': products,
        'products_total': total_products
    }
    return render(request, partial_template_name, context)

crm_core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
        Just CRM
    </title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    {% block additional_links %}
    {% endblock additional_links %}
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <main>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-2 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Just CRM</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li class="nav-item">
                                <a href="#" class="nav-link align-middle px-0">
                                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#submenu1" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> 
                                </a>
                    
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                            </li>
                            <li>
                                <a href="#submenu2" class="nav-link px-0 align-middle ">
                                    <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Clients</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'crm_core:products_view' %}" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Income</span>
                                </a>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown pb-4">
                            {% if user.is_authenticated %}
                                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                                    <span class="d-none d-sm-inline mx-1">{{ user.get_full_name }}</span>
                                </a>
                            {% else %}
                                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="d-none d-sm-inline mx-1">Account</span>
                                </a>
                            {% endif %}
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                                {% if user.is_authenticated %}
                                    <li><a class="dropdown-item" href="#">Settings</a></li>
                                    <li><a class="dropdown-item" href="#">Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    {% if user.is_staff %}
                                        <li>
                                            <a href="{% url 'admin:index' %}" class="dropdown-item">Admin Panel</a>
                                        </li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'accounts:auth' %}">Log in / Registration</a></li>
                                {% endif %}
                            </ul>

                            
                        </div>
                    </div>
                </div>
                <div class="col py-3">
                    {% block content %}
            
                    {% endblock content %}
                </div>
            </div>
        </div>
    </main>

    <footer>

    </footer>
    {% include "toasts.html" %}    
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}" ></script>
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static 'toasts.js' %}"></script>
    <script>
        htmx.config.useTemplateFragments = true;
    </script>


    {% block javascripts %}
    {% endblock javascripts %}
</body>
</html>

crm_core/templates/crm_home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home - 
{% endblock title %}

{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/crm_home.css' %}">
    
{% endblock additional_links %}

{% block content %}
    <div class="home-header-block">
        <div class="row">
            <div class="col-sm-3">
              {% include 'partials/cards/orders_card.html' %}
            </div>
            <div class="col-sm-3">
                {% include 'partials/cards/clients_card.html' %}
            </div>
            <div class="col-sm-3">
                {% include 'partials/cards/products_card.html' %}
              </div>
              <div class="col-sm-3">
                <div class="card">
                  <div class="card-body border border-1 border-success">
                    <h5 class="card-title">Income</h5>
                    <p class="card-text">Total:</p>
                  </div>
                </div>
              </div>
          </div>
    </div>
    <div class="home-main-block mt-5 row">
        <div id="spawn-form">
        </div>
        <div class="orders-list col-sm-4">
            <div class="block-header d-flex justify-content-between align-items-center">
                <h2>Orders</h2>
                <button type="button"
                    class="btn btn-outline-primary btn-sm"
                    hx-get="{% url 'crm_core:hx_add_order' %}"
                    hx-target="#spawn-form"
                    hx-swap="innerHTML"> 
                Add+
                </button>
            </div>
            <ul class="list-group items-list overflow-auto" id="orders-list">
                {% include 'partials/orders_list.html' %}
            </ul>
        </div>
        <div class="clients-list col-sm-4">
            <div class="block-header d-flex justify-content-between align-items-center">
                <h2>Clients</h2>
                <button type="button"
                    class="btn btn-outline-primary btn-sm"
                    hx-get="{% url 'crm_core:hx_add_client' %}"
                    hx-target="#spawn-form"
                    hx-swap="innerHTML"> 
                Add+
                </button>
            </div>
            <ul class="list-group items-list overflow-auto" id="clients-list">
                {% include 'partials/clients_list.html' %}
            </ul>
        </div>
        <div class="products-list col-sm-4">
            <div class="block-header d-flex justify-content-between align-items-center">
                <h2>Products</h2>
                <button type="button"
                    class="btn btn-outline-primary btn-sm"
                    hx-get="{% url 'crm_core:hx_add_product' %}"
                    hx-target="#spawn-form"
                    hx-swap="innerHTML"> 
                Add+
                </button>
            </div>
            <ul class="list-group items-list overflow-auto" id="products-list">
                {% include 'partials/products_list.html' %}
            </ul>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}

<script>
    function removeForm(event) {
        var spawnFormsBlock = document.getElementById('spawn-form');
        spawnFormsBlock.removeChild(spawnFormsBlock.firstChild);
    }
</script>
    
{% endblock javascripts %}

crm_core/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Products -
{% endblock title %}

{% block additional_links %}
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        #htmx-indicator {
            max-width: 100%;
            max-height: 35px;
        }
        .page-link:hover {
            cursor: pointer;
        }
    </style>
{% endblock additional_links %}

{% block content %}
<div class="wrapper"
    x-data="{ showAddProductForm: false }">
    <div class="header m-1">
        <div class="title p-1 text-center font-bold">
            <h1 class="text-5xl">Products</h1>
        </div>
        <div class="searchbar p-2 bg-gray-700 rounded-md d-flex">
            <input type="search" name="search" id="search" placeholder="Begin Typing To Search Product..."
                class="p-2 b-0 rounded-md w-75"
                hx-get="{% url 'crm_core:products_view' %}"
                hx-trigger="keyup changed delay:500ms, search"
                hx-target="#table-body"
                hx-wsap="innerHTML"
                hx-indicator="#htmx-indicator"
                hx-push-url="true"
            >
            <button type="button"
                    class="bg-green-600 btn-sm text-white font-bold ml-auto"
                    @click="showAddProductForm = ! showAddProductForm">
                Add Product
            </button>
        </div>
        <progress class="progress is-small is-primary mt-1 htmx-indicator" id="htmx-indicator" alt="loading..." max="100">15%</progress>
    </div>
    <form id="addProductForm" action="#" class="border border-1 p-3 rounded-custom m-1 bg-gray-200 rounded-md"
        x-show="showAddProductForm">
        <div class="row">
            <div class="mb-3 col">
                <div class="mb-3 row">
                    <div class="col">
                        <label for="title" class="form-label">Title</label>
                        <input type="text" name="title" id="title" class="form-control">
                        <div id="title" class="form-text">Input product title.</div>
                    </div>
                    <div class="col">
                        <label for="price" class="form-label">Price, $</label>
                        <input type="number" name="price" id="price" class="form-control" min="0">
                        <div id="price" class="form-text">Input product price.</div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="availability" class="form-label">Availability</label>
                    <select name="availability" id="availability" class="form-select">
                        <option value="True">Yes</option>
                        <option value="False">No</option>
                    </select>
                </div>
            </div>
            <div class="mb-3 col">
                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
                    <div id="description" class="form-text">Input product description.</div>
                </div>
            </div>
        </div>
        <input type="hidden" name="page" value="all_products">
        <div class="d-flex justify-content-between">
            <button type="submit"
                class="btn bg-green-600 btn-sm text-white font-bold"
                hx-post="{% url 'crm_core:hx_add_product' %}"
                hx-target="#table-body"
                hx-swap="innerHTML">
                Submit
            </button>
            <button type="reset" class="btn btn-outline-warning"
                @click="showAddProductForm = ! showAddProductForm">
                Cancel
            </button>
        </div>
    </form>

    <div class="main m-1">
        <div class="table-box p-2 bg-gray-200 rounded-md">
            <table class="table table-auto w-full"> 
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Availability</th>
                        <th>Created At</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="table-body">
                    {% include 'partials/products_table_body.html' %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="footer p-2 bg-white" style="border-radius: 10px;">
        {% include 'partials/paging_navigation.html' %}
    </div>
</div>
    
{% endblock content %}

{% block javascripts %}
    <script>
        document.body.addEventListener('htmx:configRequest', function(evt) {
            page_param = window.location.search;
            urlParams = new URLSearchParams(page_param);
            search_query = document.getElementById('search').value;
            if (evt.detail.path.includes('?page=')) {
                if (search_query !== '') {
                    console.log('append')
                    evt.detail.path += '&search=' + search_query
                }
            }
        });

        document.body.addEventListener('htmx:beforeSwap', function(evt) {
            if(evt.detail.xhr.status === 200){
                let form = document.getElementById('addProductForm');
                form.style.display = 'none';
                form.reset();
                
            }
        });
    </script>
{% endblock javascripts %}