accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('auth/', views.auth, name='auth'),
    path("logout/", LogoutView.as_view(), name="logout"),

    path('hx_registration/', views.hx_registration, name='hx_registration'),
    path('hx_login/', views.hx_login, name='hx_login'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_core.urls')),
    path('', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext as _

from phonenumber_field.modelfields import PhoneNumberField
from imagekit.models import ProcessedImageField
from imagekit.processors import SmartResize, Transpose

# Create your models here.
class CustomMoonUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifier
    for authentication instead of usernames.
    """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CrmUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    phone = PhoneNumberField(blank=True, region='UA')
    is_client = models.BooleanField(default=None, blank=True, null=True)
    userpic = ProcessedImageField(
        upload_to='userpics/', blank=True, default='userpics/userpic.jpg',
        processors=[Transpose(), SmartResize(480, 480)], format='JPEG',
        options={'quality': 70})

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomMoonUserManager()

    class Meta:
        pass
        ordering = ['-date_joined']

    @property
    def get_crm_url(self):
        return reverse('dashboard:user_profile_view', kwargs={'id': self.id})

    @property
    def get_user_orders(self):
        return self.orders.all()

    @property
    def phone_string(self):
        return str(self.phone)

    @property
    def get_active_orders(self):
        return self.orders.filter(active=True)

    @property
    def have_active_orders(self):
        if self.orders.filter(active=True).count() > 0:
            return True
        return False

    @property
    def have_orders(self):
        if self.orders.all().count() > 0:
            return True
        return False

    @property
    def get_uncompleted_tasks(self):
        return self.tasks.filter(completed=False).count()

    def __str__(self):
        return self.email

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.template.response import TemplateResponse

from django_htmx.http import HttpResponseClientRedirect

from accounts.models import CrmUser

# Create your views here.
def auth(request):
    template_name = 'auth_page.html'
    page = 'login'

    context = {
        'page': page,
    }
    return render(request, template_name, context)


def hx_registration(request):
    partial_template_name = 'partials/registration.html'

    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password1')

        if CrmUser.objects.filter(email=email).exists():
            messages.add_message(request, messages.ERROR, f'Error! User with email {email} already registered!')
        else:
            new_user = CrmUser.objects.create_user(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=password
            )
            new_user.is_active = True
            new_user.save()

            messages.add_message(request, messages.SUCCESS, f'Registration success! Check your {email} inbox to confirm your email!')
            return TemplateResponse(request, 'partials/login.html')


    if request.htmx:
        return render(request, partial_template_name)



def hx_login(request):
    partial_template_name = 'partials/login.html'

    if request.method == 'POST':
        print(request.POST)
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(email=email, password=password)
        if user is not None and not user.is_staff:
            messages.add_message(request, messages.ERROR, 'Error! You must log in with staff credentials!')

        elif user is not None:
            login(request, user)
            messages.add_message(request, messages.SUCCESS, 'You successfully log in!')
            return HttpResponseClientRedirect('/')
        else:
            messages.add_message(request, messages.ERROR, 'Error! Wrong email or password...')

    if request.htmx:
        return render(request, partial_template_name)

accounts/templates/partials/login.html
<div class="wrapper">
    <div class="header text-center mb-3">
        <h2>Log in</h2>
    </div>
    <div class="register-form">
        <form hx-post="{% url 'accounts:hx_login' %}"
            hx-target="#auth-wrapper"
            hx-swap="innerHTML">
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" id="email" class="form-control">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Log in</button>
        </form>
        <div class="footer mt-3">
            <p>
                Don`t have account?
                <a 
                    hx-get="{% url 'accounts:hx_registration' %}"
                    hx-target="#auth-wrapper"
                    hx-swap="innerHTML">
                    Register now!
                </a>
            </p>
        </div>
    </div>
</div>

accounts/templates/partials/registration.html
<div class="wrapper">
    <div class="header text-center mb-3">
        <h2>Registration</h2>
    </div>
    <div class="register-form">
        <form hx-post="{% url 'accounts:hx_registration' %}"
                hx-target="#auth-wrapper"
                hx-swap="innerHTML">
            <div class="mb-3">
                <label for="first_name" class="form-label">First name</label>
                <input type="text" name="first_name" id="first_name" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="last_name" class="form-label">Last name</label>
                <input type="text" name="last_name" id="last_name" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" id="email" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="password1" class="form-label">Password</label>
                <input type="password" name="password1" id="password!" class="form-control" required onchange="onChange()">
            </div>
            <div class="mb-3">
                <label for="password2" class="form-label">Confirm password</label>
                <input type="password" name="password2" id="password2" class="form-control" required onchange="onChange()">
            </div>
            <span id="password_warning" style="display: none; color:red"></span>
            <div id="password-validation" class="mb-3"></div>
            <button type="submit" class="btn btn-primary" name="register">
                Register</button>
        </form>
        <div class="footer mt-3">
            <p>
                Already registered?
                <a
                    hx-get="{% url 'accounts:hx_login' %}"
                    hx-target="#auth-wrapper"
                    hx-swap="innerHTML">
                    Log in now!
                </a>
            </p>
        </div>
    </div>
</div>

accounts/templates/partials/registration_success.html
<div class="success-registration">
    <h3>Success!</h3>
    <p>Check your email inbox to complete your registration!</p>
</div>
<div class="footer mt-3">
    <p>
        <a
            hx-get="{% url 'accounts:hx_login' %}"
            hx-target="#auth-wrapper"
            hx-swap="innerHTML">
            Back to log in!
        </a>
    </p>
</div>